oss:
  endpoint:
  accessKeyId:
  accessKeySecret:
  bucketName:
  apkBucketName:
  filedir: ie

ssdl:
  xxl:
    job:
      admin-addresses:
      accessToken:
      executor-appname: ${spring.application.name}
      executor-address:
      executor-ip:
      executor-port: 0
      executor-logpath:
      executor-logretentiondays: 30