CREATE TABLE `mc_ie_task` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT COMMENT '自增ID',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `code` varchar(50) NOT NULL COMMENT '任务编号(数据处理、导入批次号)',
  `module_code` varchar(50) NOT NULL COMMENT '业务模块编码',
  `menu_code` varchar(50) NOT NULL COMMENT '菜单编号',
  `template_code` varchar(50) NOT NULL COMMENT '模版编码',
  `template_name` varchar(150) NOT NULL COMMENT '模版名称',
  `service_model_user_id` varchar(100) NOT NULL COMMENT '业务模块导出用户唯一标识',
  `type` int(11) NOT NULL COMMENT '任务类型0导出 1导入 3数据处理',
  `state` int(11) NOT NULL DEFAULT '0' COMMENT '状态 0待启动 1执行中 2文件待上传 3失败 4成功 5暂停',
  `total_number` int(11) DEFAULT NULL COMMENT '总条数',
  `description` text COMMENT '备注',
  `query_condition_json` varchar(500) DEFAULT NULL COMMENT '查询条件json',
  `file_name` varchar(150) DEFAULT NULL COMMENT '文件名',
  `file_key` varchar(255) DEFAULT NULL COMMENT '文件服务器key',
  `schedule` int(4) NOT NULL DEFAULT '0' COMMENT '进度',
  `is_deleted` int(11) NOT NULL DEFAULT '0' COMMENT '是否删除 0否 1是',
  `complete_time` datetime DEFAULT NULL COMMENT '完成时间',
  `success_number` int(9) NOT NULL DEFAULT '0' COMMENT '成功数',
  `fail_number` int(9) NOT NULL DEFAULT '0' COMMENT '失败数',
  `import_file_key` varchar(255) DEFAULT NULL COMMENT '导入文件地址',
  `channel_code` varchar(150) DEFAULT NULL COMMENT '渠道编码',
  `execution_time` datetime DEFAULT NULL COMMENT '创建时间',
  `execution_section` varchar(50) DEFAULT NULL COMMENT '执行区间 ',
  `current_page` int(9) NOT NULL DEFAULT '0' COMMENT '当前执行分页数',
  `temp_file_save_ip` varchar(50) DEFAULT NULL COMMENT '临时文件保存服务器ip',
  `current_page_in_index` int(10) DEFAULT '0' COMMENT '当前分页内下标',
  PRIMARY KEY (`id`),
  UNIQUE KEY `undx_code` (`code`) USING BTREE,
  KEY `idx_ created_at` (`create_time`) USING BTREE,
  KEY `idx_ state` (`state`) USING BTREE,
  KEY `idx_service_module_code_user` (`module_code`,`service_model_user_id`) USING BTREE
) ENGINE=InnoDB AUTO_INCREMENT=0 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='任务管理';